### ISSUE TITLE
Fix error with old Illuminate\Foundation\Application::bindShared() method

### ISSUE THREAD

**Issue by benjdl** [mpaleo/scaffolder-theme-material#4]
In order to be compatible with Laravel 5.1+, a fix is needed:
In `/src/ScaffolderTheme/ScaffolderThemeServiceProvider.php`, line 22,
change
`$this->app->bindShare('form', function($app)`
with
`$this->app->singleton('form', function($app)`

Thanks

**Comment by mpaleo** [comment]
@benjdl Thanks to you
