### ISSUE TITLE
Missing third argument in FormBuilder::__construct() following recent update of LaravelCollective/html

### ISSUE THREAD

**Issue by benjdl** [mpaleo/scaffolder-theme-material#5]
Experiencing an issue following a recent update of LaravelCollective/html:

```
Type error: Argument 3 passed to Collective\Html\FormBuilder::__construct() must implement interface [...]
```

It happens on the view 'create.blade.php'.
The commit [https://github.com/LaravelCollective/html/commit/4c9b44a817543bd0ef7f0ca8c8a63e5556504274#diff-36caabaf080d6afdac600a28bfcd238bR101] add a new parameter Factory $view to the __construct method of FormBuilder, used in /scaffolder-theme-material/src/ScaffolderTheme/ScaffolderThemeServiceProvider.php on line 24.

In order to remain compatible with LaravelCollective/html 5.2+, we need to change this

```
$form = new MaterialThemeForm($app['html'], $app['url'], $app['session.store']->getToken());
```

with

```
$form = new MaterialThemeForm($app['html'], $app['url'], $app['view'], $app['session.store']->getToken());
```

Thanks

**Comment by mpaleo** [comment]
@benjdl the version of LaravelCollective/html is directly linked to laravel. Currently everything should be working with laravel 5.1.*. You suggest to leave LTS and point to the latest stable release of laravel (5.2 right now)?

[LaravelCollective/html 5.1 branch - composer require](https://github.com/LaravelCollective/html/blob/5.1/composer.json#L14)

[LaravelCollective/html 5.2 branch - composer require](https://github.com/LaravelCollective/html/blob/5.2/composer.json#L20)

**Comment by benjdl** [comment]
In my current project I had to update LaravelCollective/html to the 5.2 that's why I just leave here an issue in case of someone encounter the same problem and want to fix it. Everything ok on 5.1 ;)

**Comment by mpaleo** [comment]
@benjdl ok thanks :), but what do you think about what version of laravel we should support ? 5.2 ?
